//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScaler) DeepCopyInto(out *AutoScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScaler.
func (in *AutoScaler) DeepCopy() *AutoScaler {
	if in == nil {
		return nil
	}
	out := new(AutoScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalerList) DeepCopyInto(out *AutoScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalerList.
func (in *AutoScalerList) DeepCopy() *AutoScalerList {
	if in == nil {
		return nil
	}
	out := new(AutoScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalerSpec) DeepCopyInto(out *AutoScalerSpec) {
	*out = *in
	in.Pattern.DeepCopyInto(&out.Pattern)
	in.Implementation.DeepCopyInto(&out.Implementation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalerSpec.
func (in *AutoScalerSpec) DeepCopy() *AutoScalerSpec {
	if in == nil {
		return nil
	}
	out := new(AutoScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalerStatus) DeepCopyInto(out *AutoScalerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrefillReplicas != nil {
		in, out := &in.PrefillReplicas, &out.PrefillReplicas
		*out = new(int32)
		**out = **in
	}
	if in.DecodeReplicas != nil {
		in, out := &in.DecodeReplicas, &out.DecodeReplicas
		*out = new(int32)
		**out = **in
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalerStatus.
func (in *AutoScalerStatus) DeepCopy() *AutoScalerStatus {
	if in == nil {
		return nil
	}
	out := new(AutoScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamoPlannerConfig) DeepCopyInto(out *DynamoPlannerConfig) {
	*out = *in
	out.Profiling = in.Profiling
	if in.MetricsEndpoint != nil {
		in, out := &in.MetricsEndpoint, &out.MetricsEndpoint
		*out = new(MetricsEndpointConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamoPlannerConfig.
func (in *DynamoPlannerConfig) DeepCopy() *DynamoPlannerConfig {
	if in == nil {
		return nil
	}
	out := new(DynamoPlannerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Implementation) DeepCopyInto(out *Implementation) {
	*out = *in
	if in.DynamoPlanner != nil {
		in, out := &in.DynamoPlanner, &out.DynamoPlanner
		*out = new(DynamoPlannerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Implementation.
func (in *Implementation) DeepCopy() *Implementation {
	if in == nil {
		return nil
	}
	out := new(Implementation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsEndpointConfig) DeepCopyInto(out *MetricsEndpointConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsEndpointConfig.
func (in *MetricsEndpointConfig) DeepCopy() *MetricsEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDDisaggregatedPattern) DeepCopyInto(out *PDDisaggregatedPattern) {
	*out = *in
	out.Prefill = in.Prefill
	out.Decode = in.Decode
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDDisaggregatedPattern.
func (in *PDDisaggregatedPattern) DeepCopy() *PDDisaggregatedPattern {
	if in == nil {
		return nil
	}
	out := new(PDDisaggregatedPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pattern) DeepCopyInto(out *Pattern) {
	*out = *in
	if in.PDDisaggregated != nil {
		in, out := &in.PDDisaggregated, &out.PDDisaggregated
		*out = new(PDDisaggregatedPattern)
		**out = **in
	}
	if in.Unified != nil {
		in, out := &in.Unified, &out.Unified
		*out = new(UnifiedPattern)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pattern.
func (in *Pattern) DeepCopy() *Pattern {
	if in == nil {
		return nil
	}
	out := new(Pattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingConfig) DeepCopyInto(out *ProfilingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingConfig.
func (in *ProfilingConfig) DeepCopy() *ProfilingConfig {
	if in == nil {
		return nil
	}
	out := new(ProfilingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleScalingConfig) DeepCopyInto(out *RoleScalingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleScalingConfig.
func (in *RoleScalingConfig) DeepCopy() *RoleScalingConfig {
	if in == nil {
		return nil
	}
	out := new(RoleScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnifiedPattern) DeepCopyInto(out *UnifiedPattern) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnifiedPattern.
func (in *UnifiedPattern) DeepCopy() *UnifiedPattern {
	if in == nil {
		return nil
	}
	out := new(UnifiedPattern)
	in.DeepCopyInto(out)
	return out
}
