apiVersion: inference-extension.rolebasedgroup.io/v1alpha1
kind: AutoScaler
metadata:
  name: sglang-pd-inference
  namespace: demo
spec:
  scalingInterval: 60
  pattern:
    PDDisaggregated:
      prefill:
        roleName: prefill
        maxReplicas: 4
        minReplicas: 1
      decode:
        roleName: decode
        maxReplicas: 4
        minReplicas: 1
  implementation:
    DynamoPlanner:
      modelName: "qwen3-6"
      ttft: 500
      itl: 50
      loadPredictor: arima
      predictionWindow: 10
      noCorrection: false
      dryRun: false
      metricsEndpoint:
        metricSource: sglang
        port: 9091
      profiling:
        image: "registry-cn-hangzhou.ack.aliyuncs.com/dev/rbg-role-autoscaler-profiler:v0.0.1"
